version: "3"
services:
  s3:
    image: minio/minio:RELEASE.2023-08-23T10-07-06Z
    container_name: minio
    hostname: minio
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=minio"
    volumes:
      - ./minio:/opt/bin/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"